name: textmining-infoprosCHAPTER1-binderized
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - r-base=4.1.3
  - r-irkernel>=1.1
  - r-ggsci
  - r-ggplot2
  - r-Matrix
  - r-stringi
  - r-tm
  - r-NLP
  - r-cluster
  - r-wordcloud
  - r-RColorBrewer
  - r-SparseM
  - r-proxy
  - r-readr
  - r-fpc
  - r-factoextra
  - r-igraph
  - r-text2vec
